name: Run Tests
on: push
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: 4
        python-version: ["3.9", "3.10"]
    env:
      PYTHON_VERSION: ${{matrix.python-version}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Test with tox
        run: tox
        env:
          TOXENV: py${{matrix.python-version}}
